kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: publish
  pull: if-not-exists 
  image: plugins/docker
  settings:
    insecure: true
    username: 
      from_secret: username
    password:
      from_secret: password 
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/maximlab/python
    dockerfile: Dockerfile
    tags: cos
